--다중컬럼
--#7201
SELECT GRADE 학년,NAME 이름,HEIGHT 키
FROM T_STUDENT 
WHERE (grade,HEIGHT)IN 
(SELECT grade,MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE)
ORDER BY 1 ASC ;
--#7202
SELECT * FROM T_PROFESSOR;
SELECT * FROM T_DEPARTMENT ;

SELECT p.PROFNO 교수번호, p.NAME 교수명, p.HIREDATE 입사일, d.DNAME 학과명
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO =d.DEPTNO AND (p.deptno,p.HIREDATE)IN 
(SELECT DEPTNO,MIN(HIREDATE) FROM T_PROFESSOR GROUP BY DEPTNO)
ORDER BY 4 ASC ;

--#7203
SELECT * FROM T_EMP2 ;

SELECT NAME 사원명,post 직급,pay 연봉
FROM T_EMP2 
WHERE (post, PAY ) IN 
(SELECT POST, MAX(Pay) FROM T_EMP2 GROUP BY POST)
ORDER BY 3 ASC;

--#7204
SELECT * FROM T_DEPT2 ;
SELECT * FROM T_EMP2 ;

SELECT d.DNAME 부서명, e.NAME 직원명, e.PAY 연봉
FROM T_EMP2 e, T_DEPT2 d
WHERE e.DEPTNO =d.DCODE AND e.PAY <ALL (SELECT AVG(pay) FROM T_EMP2 GROUP BY deptno)
ORDER BY 3;


--#7205
SELECT a.NAME 사원이름, NVL(a.post,' ') 직급, a.pay 연봉
FROM T_EMP2 a
WHERE pay>=(SELECT AVG(b.PAY) FROM t_emp2 b WHERE NVL(a.post,' ')=NVL(b.post,' '));



--#7206
SELECT NAME 사원이름,(SELECT DNAME FROM T_DEPT2 d WHERE e.DEPTNO =d.DCODE ) 부서이름
FROM T_EMP2 e,T_DEPT2 d;

