--묵시적 자동 형변환 예
SELECT 1+1 FROM dual;
SELECT '1'+1 FROM dual;

--TO_CHAR 함수(날짜-> 문자)

SELECT 
	SYSDATE,
	TO_CHAR(SYSDATE,'YYYY') 연도4자리,
	TO_CHAR(SYSDATE,'RRRR') 연도Y2K버그이후,
	TO_CHAR(SYSDATE,'YY') 연도2자리,
	TO_CHAR(SYSDATE,'Year') 연도영문 
FROM dual;

SELECT 
	TO_CHAR(SYSDATE,'DD') 일숫자2자리,
	TO_CHAR(SYSDATE,'DDTH') 몇번째날,
	TO_CHAR(SYSDATE,'DAY') 요일,
	TO_CHAR(SYSDATE,'Dy') 요일 앞자리
FROM dual;

SELECT 
	TO_CHAR(SYSDATE, 'MON') 월3자리,  -- 7월
	TO_CHAR(SYSDATE, 'MONTH')  월전체,  -- 7월
	TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE=ENGLISH') 월영문3자리,  -- JUL
	TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(대)", -- JULY
	TO_CHAR(SYSDATE, 'month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(소)",  -- july
	TO_CHAR(SYSDATE, 'Month', 'NLS_DATE_LANGUAGE=ENGLISH')  "월영문전체(첫글자대)" -- July
FROM DUAL;

SELECT 
	TO_CHAR(SYSDATE, 'HH24') 시24hr,
	TO_CHAR(SYSDATE, 'HH')  시12hr,
	TO_CHAR(SYSDATE, 'MI') 분,
	TO_CHAR(SYSDATE, 'SS') 초,
	TO_CHAR(susdate,'HH:MI:SS');
FROM dual;

SELECT 
	TO_CHAR(SYSDATE,'YY/MM/DD'),SYSDATE 날짜 
FROM dual;

SELECT SYSDATE,TO_CHAR(sysdate,'yyyy"년"MM"월"DD"일" HH24"시"MI"분"SS"초"') 
FROM dual;

SELECT name, TO_CHAR(BIRTHDAY,'YYYY"-"MM"-"DD') 
FROM T_STUDENT
WHERE TO_CHAR(BIRTHDAY,'MM')='03';


-- TO_CHAR : 대소문자 지정예
SELECT
SYSDATE,
TO_CHAR(SYSDATE, 'Dy Month DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A1,
TO_CHAR(SYSDATE, 'dy month dd, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A2,
TO_CHAR(SYSDATE, 'DY MONTH DD, YYYY', 'NLS_DATE_LANGUAGE=ENGLISH') AS A3
FROM DUAL;

SELECT 
	1234,
	TO_CHAR(1234,'9999') "9하나당 1자리",
	TO_CHAR(1234,'099999') "빈자리 0으로",
	TO_CHAR(1234,'$9999') "빈자리 $로",
	TO_CHAR(1234.1234,'9999.99') "소숫점이하 2자리",
	TO_CHAR(12345,'99,999') "천단위에 구분기호" --9가 5자리까지밖에 안됨. 문자열 직접 변경해줘야함.
FROM dual;

--#4303
SELECT NAME,TO_CHAR(NVL(bonus,0)+(pay*12),'99,999')
FROM T_PROFESSOR 
WHERE DEPTNO =101;

--TO_NUMBER()
SELECT TO_NUMBER('123,44')
FROM  DUAL;

--TO_DATE(): 문자-> 날짜
SELECT TO_DATE('2020-12-08','YYYY-MM-DD') TO_DATE 
FROM dual;

--#4304
SELECT NAME,TO_CHAR(HIREDATE,'YYYY-MM-DD') 입사일,TO_CHAR(PAY*12,'99,999') 연봉,TO_CHAR((PAY*12)*1.1,'99,999') 
FROM T_PROFESSOR
--WHERE SUBSTR(HIREDATE,1,4)>'2000' 
WHERE TO_CHAR(HIREDATE ,'YYYY')<'2000'; 