--INITCAP() 함수

--#4101
SELECT INITCAP('pretty girl') 
FROM dual;

--#4102
SELECT INITCAP(ID) 
FROM T_STUDENT 
WHERE DEPTNO1 =201;

--LOWER(),UPPER()
--#4103
SELECT NAME 이름, ID ,LOWER(ID) 소문자, UPPER(ID) 대문자 
FROM T_STUDENT 
WHERE DEPTNO1 =201;

--#4104
SELECT NAME 이름,ID,LENGTH(ID) 글자수
FROM T_STUDENT 
WHERE LENGTH(ID)>=9;

--#4105
SELECT NAME 이름,LENGTH(NAME) 길이,LENGTHB(NAME) 바이트 
FROM T_STUDENT 
WHERE DEPTNO1 =201;

--#4106
SELECT CONCAT(NAME,POSITION) 교수님명단
FROM T_PROFESSOR 
WHERE DEPTNO =101;

--#4107
SELECT *
FROM T_STUDENT ;
SELECT NAME,SUBSTR(JUMIN,1,6) 생년월일 
FROM T_STUDENT 
WHERE DEPTNO1 =101;

--#4108
SELECT NAME ,SUBSTR(JUMIN,1,6) 생년월일 
FROM T_STUDENT 
WHERE SUBSTR(JUMIN,3,2)='08'; 
--where jumin like '__08%';

--#4109
SELECT NAME,JUMIN 
FROM T_STUDENT 
WHERE GRADE=4 AND SUBSTR(JUMIN,7,1)='2';

--#4110
SELECT NAME ,TEL ,INSTR(TEL,')') 위치 
FROM T_STUDENT 
WHERE DEPTNO1 =101;

--#4111
SELECT NAME ,TEL ,SUBSTR(TEL ,1,INSTR(TEL,')')-1) --지역번호 
FROM T_STUDENT 
WHERE DEPTNO1 =101;



SELECT name, tel, substr(tel,1,instr(tel,')')-1)
FROM T_STUDENT 
WHERE deptno1=101;

--LTRIM(),RTRIM,TRIM()
SELECT 
	LTRIM('슈퍼슈퍼슈가맨','슈퍼'),
	LTRIM('슈퍼슈퍼슈가맨','슈'),
	LTRIM('   슈퍼슈퍼슈가맨',' '),
	LTRIM('   슈퍼슈퍼슈가맨'),--공백제거
	rtrim('우측 공백 제거   '),
	TRIM('   슈퍼맨    '),--좌우 공백 제거
	LTRIM('******10000','*')
FROM dual;

--#4117
SELECT RTRIM(dname,'부') 
FROM T_DEPT2 ;

--#4118
SELECT REPLACE(NAME,SUBSTR(NAME,1,1),'#') 학생
FROM  T_STUDENT 
WHERE DEPTNO1 =102;

--#4119
SELECT REPLACE(NAME,SUBSTR(NAME,2,1),'#') 학생
FROM T_STUDENT 
WHERE DEPTNO1 =101;

--#4120
SELECT NAME,REPLACE(JUMIN ,SUBSTR(JUMIN ,7),'*******') 주민번호
FROM T_STUDENT 
WHERE DEPTNO1 =101;

--#4121
SELECT NAME ,TEL,REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,')')+1,3),'###')
FROM T_STUDENT 
WHERE DEPTNO1 =102;


